/**:
  ros__parameters:
    source_list: []
    default:
      Revolute_110: 0.0
      Revolute_111: -0.32
      Revolute_112: 2.00
      Revolute_113: 0.0
      Revolute_114: -0.32
      Revolute_115: 2.00
      Revolute_116: 0.0
      Revolute_117: -0.32
      Revolute_118: 2.00
      Revolute_119: 0.0
      Revolute_120: -0.32
      Revolute_121: 2.00
